apiVersion: v1
kind: Datasource
metadata:
  name: prometheus-llm-d
  project: llm-d-monitoring
spec:
  default: true
  plugin:
    kind: PrometheusDatasource
    spec:
      directUrl: http://prometheus:9090
      # Alternative configurations for different environments
      # For OpenShift AI environments:
      # directUrl: https://thanos-querier-openshift-monitoring.apps.cluster.example.com
      # For development:
      # directUrl: http://localhost:9090
      
      # Authentication configuration for production environments
      # Option 1: Basic authentication
      # proxy:
      #   kind: HTTPProxy
      #   spec:
      #     headers:
      #       Authorization: "Bearer ${PROMETHEUS_TOKEN}"
      
      # Option 2: NEW v0.51.1 OAuth support
      # oauth:
      #   kind: OAuth2
      #   spec:
      #     tokenUrl: https://auth.example.com/oauth2/token
      #     clientId: llm-d-monitoring
      #     clientSecret:
      #       name: oauth-secret
      #       key: client-secret
      #     scopes:
      #       - prometheus:read
      #       - metrics:query
      
      # TLS configuration for secure connections
      # tls:
      #   insecureSkipVerify: false
      #   serverName: "prometheus.example.com"
      
      # Query timeout configuration
      httpConfig:
        queryTimeout: 300s
        connectTimeout: 30s
        
  # Health check configuration
  healthCheck:
    enabled: true
    interval: 30s
    timeout: 10s
    
  # Rate limiting to prevent overwhelming Prometheus
  rateLimiting:
    enabled: true
    requestsPerSecond: 100
    burstSize: 200